### ISSUE TITLE
Profile edit page is needed

### ISSUE THREAD

**Issue by konpyu** [shumipro/meetapp#43]
I tried to update my github account / website but I couldn't find the link to edit page.
Please tell me the link if I missed simply.

![sc 2015-05-12 21 02 56](https://cloud.githubusercontent.com/assets/997966/7586699/7194a3e6-f8ea-11e4-923c-b1c8896e3046.png)

**Comment by tejitak** [comment]
Hi @konpyu ,
Sorry for your inconvenience. I think it is now fixed. The condition to show edit was wrong. It was 'the account has at least one admin idea'. 

Could you please try to access the page again since my account always shows the edit menu?
A menu to edit profile would be located at the top of the page!

**Comment by konpyu** [comment]
Thank you! Updating profile of mine was successfully finished!
